import { youtubeSources } from './youtube-sources';

export const categories = [
  { id: 'morning-vinyl', title: 'Morning Vinyl', eyebrow: 'SOFT START', description: 'Misty melodies, slow light and the first cup of chai.', time: '06:00—10:00', tint: '#b7783f' },
  { id: 'monsoon-melodies', title: 'Monsoon Melodies', eyebrow: 'RAIN ON TIN', description: 'Cloud-heavy classics for windows left slightly open.', time: '10:00—14:00', tint: '#6d7462' },
  { id: 'twilight-classics', title: 'Twilight Classics', eyebrow: 'GOLDEN HOUR', description: 'Songs that soften the room as daylight disappears.', time: '17:00—20:00', tint: '#9b4f2c' },
  { id: 'kishore-after-dark', title: 'Kishore After Dark', eyebrow: 'LATE SHOW', description: 'Velvet baritone, dim lamps and one last record.', time: '22:00—LATE', tint: '#43372f' },
];

const catalog = [
  { id:'waqt-ne-kiya', title:'Waqt Ne Kiya Kya Haseen Sitam', artist:'Geeta Dutt', film:'Kaagaz Ke Phool', year:1959, duration:'3:31', mood:'twilight', signature:true },
  { id:'lag-jaa-gale', title:'Lag Jaa Gale', artist:'Lata Mangeshkar', film:'Woh Kaun Thi?', year:1964, duration:'4:18', mood:'monsoon', signature:true },
  { id:'aap-ki-nazron', title:'Aap Ki Nazron Ne Samjha', artist:'Lata Mangeshkar', film:'Anpadh', year:1962, duration:'3:54', mood:'morning', signature:true },
  { id:'na-tum-hamen', title:'Na Tum Hamen Jano', artist:'Hemant Kumar', film:'Baat Ek Raat Ki', year:1962, duration:'3:28', mood:'after-dark', signature:true },
  { id:'kuch-dil-ne-kaha', title:'Kuch Dil Ne Kaha', artist:'Lata Mangeshkar', film:'Anupama', year:1966, duration:'4:08', mood:'morning', signature:true },
  { id:'woh-shaam', title:'Woh Shaam Kuch Ajeeb Thi', artist:'Kishore Kumar', film:'Khamoshi', year:1969, duration:'4:44', mood:'twilight', signature:true },
  { id:'kahin-door', title:'Kahin Door Jab Din Dhal Jaye', artist:'Mukesh', film:'Anand', year:1971, duration:'5:37', mood:'twilight', signature:true },
  { id:'raina-beeti-jaye', title:'Raina Beeti Jaye', artist:'Lata Mangeshkar', film:'Amar Prem', year:1972, duration:'6:18', mood:'after-dark', signature:true },
  { id:'tere-bina', title:'Tere Bina Zindagi Se Koi', artist:'Lata Mangeshkar, Kishore Kumar', film:'Aandhi', year:1975, duration:'5:55', mood:'after-dark', signature:true },
  { id:'dil-dhoondta-hai', title:'Dil Dhoondta Hai', artist:'Bhupinder Singh, Lata Mangeshkar', film:'Mausam', year:1975, duration:'7:42', mood:'monsoon', signature:true },
  { id:'awara-hoon', title:'Awara Hoon', artist:'Mukesh', film:'Awaara', year:1951, duration:'3:03', mood:'morning' },
  { id:'suhana-safar', title:'Suhana Safar Aur Yeh Mausam Haseen', artist:'Mukesh', film:'Madhumati', year:1958, duration:'3:49', mood:'morning' },
  { id:'aaja-re-pardesi', title:'Aaja Re Pardesi', artist:'Lata Mangeshkar', film:'Madhumati', year:1958, duration:'4:28', mood:'monsoon' },
  { id:'ajeeb-dastan', title:'Ajeeb Dastan Hai Yeh', artist:'Lata Mangeshkar', film:'Dil Apna Aur Preet Parai', year:1960, duration:'5:15', mood:'twilight' },
  { id:'khoya-khoya-chand', title:'Khoya Khoya Chand', artist:'Mohammed Rafi', film:'Kala Bazar', year:1960, duration:'4:42', mood:'after-dark' },
  { id:'chaudhvin-ka-chand', title:'Chaudhvin Ka Chand Ho', artist:'Mohammed Rafi', film:'Chaudhvin Ka Chand', year:1960, duration:'3:41', mood:'after-dark' },
  { id:'allah-tero-naam', title:'Allah Tero Naam', artist:'Lata Mangeshkar', film:'Hum Dono', year:1961, duration:'3:38', mood:'morning' },
  { id:'o-sajna', title:'O Sajna Barkha Bahar Aayi', artist:'Lata Mangeshkar', film:'Parakh', year:1960, duration:'3:10', mood:'monsoon' },
  { id:'yeh-nayan', title:'Yeh Nayan Dare Dare', artist:'Hemant Kumar', film:'Kohraa', year:1964, duration:'4:06', mood:'after-dark' },
  { id:'abhi-na-jao', title:'Abhi Na Jao Chhod Kar', artist:'Mohammed Rafi, Asha Bhosle', film:'Hum Dono', year:1961, duration:'4:15', mood:'twilight' },
  { id:'naina-barse', title:'Naina Barse Rimjhim Rimjhim', artist:'Lata Mangeshkar', film:'Woh Kaun Thi?', year:1964, duration:'6:16', mood:'monsoon' },
  { id:'diwana-hua-badal', title:'Diwana Hua Badal', artist:'Mohammed Rafi, Asha Bhosle', film:'Kashmir Ki Kali', year:1964, duration:'5:55', mood:'monsoon' },
  { id:'gaata-rahe', title:'Gaata Rahe Mera Dil', artist:'Kishore Kumar, Lata Mangeshkar', film:'Guide', year:1965, duration:'4:50', mood:'morning' },
  { id:'aaj-phir-jeene', title:'Aaj Phir Jeene Ki Tamanna Hai', artist:'Lata Mangeshkar', film:'Guide', year:1965, duration:'3:58', mood:'morning' },
  { id:'din-dhal-jaye', title:'Din Dhal Jaye', artist:'Mohammed Rafi', film:'Guide', year:1965, duration:'4:52', mood:'twilight' },
  { id:'piya-tose', title:'Piya Tose Naina Laage Re', artist:'Lata Mangeshkar', film:'Guide', year:1965, duration:'8:26', mood:'twilight' },
  { id:'pukarta-chala', title:'Pukarta Chala Hoon Main', artist:'Mohammed Rafi', film:'Mere Sanam', year:1965, duration:'3:51', mood:'morning' },
  { id:'mere-sapno-ki-rani', title:'Mere Sapno Ki Rani', artist:'Kishore Kumar', film:'Aradhana', year:1969, duration:'4:58', mood:'morning' },
  { id:'roop-tera', title:'Roop Tera Mastana', artist:'Kishore Kumar', film:'Aradhana', year:1969, duration:'3:45', mood:'after-dark' },
  { id:'tum-pukar-lo', title:'Tum Pukar Lo', artist:'Hemant Kumar', film:'Khamoshi', year:1969, duration:'3:46', mood:'after-dark' },
  { id:'phoolon-ke-rang', title:'Phoolon Ke Rang Se', artist:'Kishore Kumar', film:'Prem Pujari', year:1970, duration:'4:52', mood:'morning' },
  { id:'zindagi-kaisi', title:'Zindagi Kaisi Hai Paheli', artist:'Manna Dey', film:'Anand', year:1971, duration:'3:29', mood:'twilight' },
  { id:'yeh-shaam-mastani', title:'Yeh Shaam Mastani', artist:'Kishore Kumar', film:'Kati Patang', year:1971, duration:'4:42', mood:'twilight' },
  { id:'musafir-hoon', title:'Musafir Hoon Yaaron', artist:'Kishore Kumar', film:'Parichay', year:1972, duration:'3:19', mood:'morning' },
  { id:'chingari', title:'Chingari Koi Bhadke', artist:'Kishore Kumar', film:'Amar Prem', year:1972, duration:'5:36', mood:'after-dark' },
  { id:'ek-pyar-ka-nagma', title:'Ek Pyar Ka Nagma Hai', artist:'Lata Mangeshkar, Mukesh', film:'Shor', year:1972, duration:'5:56', mood:'twilight' },
  { id:'o-mere-dil-ke-chain', title:'O Mere Dil Ke Chain', artist:'Kishore Kumar', film:'Mere Jeevan Saathi', year:1972, duration:'4:32', mood:'after-dark' },
  { id:'chura-liya', title:'Chura Liya Hai Tumne Jo Dil Ko', artist:'Asha Bhosle, Mohammed Rafi', film:'Yaadon Ki Baaraat', year:1973, duration:'4:49', mood:'after-dark' },
  { id:'pal-pal', title:'Pal Pal Dil Ke Paas', artist:'Kishore Kumar', film:'Blackmail', year:1973, duration:'5:29', mood:'twilight' },
  { id:'bheegi-bheegi', title:'Bheegi Bheegi Raaton Mein', artist:'Kishore Kumar, Lata Mangeshkar', film:'Ajanabee', year:1974, duration:'3:55', mood:'monsoon' },
  { id:'kabhi-kabhie', title:'Kabhi Kabhie Mere Dil Mein', artist:'Mukesh', film:'Kabhi Kabhie', year:1976, duration:'5:32', mood:'twilight' },
  { id:'naam-gum-jayega', title:'Naam Gum Jayega', artist:'Lata Mangeshkar, Bhupinder Singh', film:'Kinara', year:1977, duration:'5:15', mood:'after-dark' },
  { id:'aap-ki-ankhon', title:'Aap Ki Ankhon Mein Kuch', artist:'Kishore Kumar, Lata Mangeshkar', film:'Ghar', year:1978, duration:'4:09', mood:'after-dark' },
  { id:'baharon-phool-barsao', title:'Baharon Phool Barsao', artist:'Mohammed Rafi', film:'Suraj', year:1966, duration:'4:27', mood:'morning' },
  { id:'aaj-kal-tere-mere', title:'Aaj Kal Tere Mere Pyar Ke Charche', artist:'Mohammed Rafi, Suman Kalyanpur', film:'Brahmachari', year:1968, duration:'5:09', mood:'morning' },
  { id:'kora-kagaz-tha', title:'Kora Kagaz Tha Yeh Man Mera', artist:'Kishore Kumar, Lata Mangeshkar', film:'Aradhana', year:1969, duration:'5:38', mood:'twilight' },
  { id:'rangeela-re', title:'Rangeela Re', artist:'Lata Mangeshkar', film:'Prem Pujari', year:1970, duration:'6:17', mood:'twilight' },
  { id:'zindagi-ek-safar', title:'Zindagi Ek Safar Hai Suhana', artist:'Kishore Kumar', film:'Andaz', year:1971, duration:'4:20', mood:'morning' },
  { id:'kuchh-to-log', title:'Kuchh To Log Kahenge', artist:'Kishore Kumar', film:'Amar Prem', year:1972, duration:'4:19', mood:'after-dark' },
  { id:'main-shayar-to-nahin', title:'Main Shayar To Nahin', artist:'Shailendra Singh', film:'Bobby', year:1973, duration:'5:33', mood:'twilight' },
  { id:'mora-gora-ang', title:'Mora Gora Ang Lai Le', artist:'Lata Mangeshkar', film:'Bandini', year:1963, duration:'3:18', mood:'morning' },
  { id:'man-re-tu-kahe', title:'Man Re Tu Kahe Na Dheer Dhare', artist:'Mohammed Rafi', film:'Chitralekha', year:1964, duration:'3:15', mood:'after-dark' },
  { id:'kya-janu-sajan', title:'Kya Janu Sajan', artist:'Lata Mangeshkar', film:'Baharon Ke Sapne', year:1967, duration:'5:39', mood:'monsoon' },
  { id:'beeti-na-bitai-raina', title:'Beeti Na Bitai Raina', artist:'Lata Mangeshkar, Bhupinder Singh', film:'Parichay', year:1972, duration:'3:14', mood:'after-dark' },
  { id:'tere-mere-milan', title:'Tere Mere Milan Ki Yeh Raina', artist:'Kishore Kumar, Lata Mangeshkar', film:'Abhimaan', year:1973, duration:'4:55', mood:'monsoon' },
  { id:'teri-bindiya-re', title:'Teri Bindiya Re', artist:'Lata Mangeshkar, Mohammed Rafi', film:'Abhimaan', year:1973, duration:'4:32', mood:'morning' },
  { id:'is-mod-se-jate-hain', title:'Is Mod Se Jate Hain', artist:'Kishore Kumar, Lata Mangeshkar', film:'Aandhi', year:1975, duration:'4:56', mood:'twilight' },
  { id:'aap-yun-faaslon-se', title:'Aap Yun Faaslon Se', artist:'Lata Mangeshkar', film:'Shankar Hussain', year:1977, duration:'4:14', mood:'after-dark' },
  { id:'aane-wala-pal', title:'Aane Wala Pal Jane Wala Hai', artist:'Kishore Kumar', film:'Gol Maal', year:1979, duration:'4:39', mood:'twilight' },
  { id:'yeh-raat-bheegi', title:'Yeh Raat Bheegi Bheegi', artist:'Manna Dey, Lata Mangeshkar', film:'Chori Chori', year:1956, duration:'4:30', mood:'monsoon' }
];

export const tracks = catalog.map(track => ({
  ...track,
  youtubeId: youtubeSources[track.id]?.id ?? null,
  sourceChannel: youtubeSources[track.id]?.channel ?? null,
}));

export const editorial = {
  issue: 'ARCHIVE NOTE · NO. 07',
  title: 'When silence became an instrument',
  deck: 'Inside the shadow-lit sound of Hemant Kumar, where every pause carries the weight of a confession.',
  readTime: '8 minute read'
};
