// Official label or YouTube Music Topic sources. Metadata only; no copyrighted audio is bundled.
export const youtubeSources = {
  'waqt-ne-kiya': { id: 'pOR3pa3Wiq4', channel: "Geeta Dutt - Topic" },
  'lag-jaa-gale': { id: 'g3S0MklEHy8', channel: "Lata Mangeshkar - Topic" },
  'aap-ki-nazron': { id: 'BxG6VqAV01Y', channel: "Saregama Music" },
  'na-tum-hamen': { id: 'AuF-N8V3JXg', channel: "Saregama Music" },
  'kuch-dil-ne-kaha': { id: '69dnqIFfrnE', channel: "Shemaroo Filmi Gaane" },
  'woh-shaam': { id: 'MDXFi3avqo0', channel: "Goldmines Gaane Sune Ansune" },
  'kahin-door': { id: 'ALcunSNj794', channel: "Saregama Music" },
  'raina-beeti-jaye': { id: '8vEvbY51VWw', channel: "Lata Mangeshkar - Topic" },
  'tere-bina': { id: 'EiUDYzqdz2U', channel: "Saregama Music" },
  'dil-dhoondta-hai': { id: 'XJnL4GUqB40', channel: "Bhupinder - Topic" },
  'awara-hoon': { id: 'Q3Sy8rdD_3Y', channel: "Saregama Music" },
  'suhana-safar': { id: 'pK2WFw8nypc', channel: "Saregama Music" },
  'aaja-re-pardesi': { id: '9MBCNhf-YjM', channel: "Lata Mangeshkar - Topic" },
  'ajeeb-dastan': { id: 'AU-hut9lGQ4', channel: "Saregama Music" },
  'khoya-khoya-chand': { id: 'Luh1HXCzML0', channel: "Mohammed Rafi - Topic" },
  'chaudhvin-ka-chand': { id: '936C_e631RU', channel: "SuperHit Gaane" },
  'allah-tero-naam': { id: 'hS1wq8ZYsKI', channel: "Lata Mangeshkar - Topic" },
  'o-sajna': { id: '25qBQZMtg5w', channel: "Lata Mangeshkar - Topic" },
  'yeh-nayan': { id: 'BCDU8nHryaE', channel: "Saregama Music" },
  'abhi-na-jao': { id: 'oDfK3RfSlKk', channel: "Saregama Music" },
  'naina-barse': { id: '2d8iFAUibFE', channel: "Saregama Music" },
  'diwana-hua-badal': { id: '9A6wJf6-Mqw', channel: "Saregama Music" },
  'gaata-rahe': { id: 'dbZW8Dral8o', channel: "Shemaroo Filmi Gaane" },
  'aaj-phir-jeene': { id: 'sACLGUkLo3Q', channel: "Saregama Music" },
  'din-dhal-jaye': { id: '6gcGxoGiOTE', channel: "Mohammed Rafi - Topic" },
  'piya-tose': { id: 'EF3Tlo-jSq4', channel: "Lata Mangeshkar - Topic" },
  'pukarta-chala': { id: 'GRo1dONJ74o', channel: "Mohammed Rafi - Topic" },
  'mere-sapno-ki-rani': { id: 'RVeLrwoB_xw', channel: "Kishore Kumar - Topic" },
  'roop-tera': { id: 'zqjSgAj9NWo', channel: "Kishore Kumar - Topic" },
  'tum-pukar-lo': { id: 'SbPps7B9J8c', channel: "Hemanta Mukherjee   - Topic" },
  'phoolon-ke-rang': { id: 'QGedVe-IEVk', channel: "Saregama Music" },
  'zindagi-kaisi': { id: '8WHxCww2gUk', channel: "Saregama Music" },
  'yeh-shaam-mastani': { id: 'E2MAYaNWb18', channel: "Kishore Kumar - Topic" },
  'musafir-hoon': { id: 'Yd62azPw4hI', channel: "Saregama Music" },
  'chingari': { id: 'EUC7Phj7ngE', channel: "Kishore Kumar - Topic" },
  'ek-pyar-ka-nagma': { id: 'H2BTCPW3Hw8', channel: "Saregama Music" },
  'o-mere-dil-ke-chain': { id: 'qWRw17tQ8UA', channel: "Shemaroo Filmi Gaane" },
  'chura-liya': { id: 'KT0NlItK86A', channel: "Asha Bhosle - Topic" },
  'pal-pal': { id: '3LZAUjeIwcI', channel: "UMusicIndiaVEVO" },
  'bheegi-bheegi': { id: 'RplhpZ_YEcU', channel: "Lata Mangeshkar - Topic" },
  'kabhi-kabhie': { id: 'BB6KvXQx090', channel: "Saregama Music" },
  'naam-gum-jayega': { id: 'CX5bLCWzotc', channel: "Saregama Music" },
  'aap-ki-ankhon': { id: 'dmm5lM9BR8o', channel: "Kishore Kumar - Topic" },
  'baharon-phool-barsao': { id: 'McP9D114BfU', channel: "Rajshri" },
  'aaj-kal-tere-mere': { id: 'z4ygQA9G0MY', channel: "Suman Kalyanpur - Topic" },
  'kora-kagaz-tha': { id: 'OKHH4Tfssg8', channel: "Lata Mangeshkar - Topic" },
  'rangeela-re': { id: 'fdS4jWT_7vE', channel: "Lata Mangeshkar - Topic" },
  'zindagi-ek-safar': { id: 'KgyOAgq7EvE', channel: "Kishore Kumar - Topic" },
  'kuchh-to-log': { id: 'X6q7BVZXOUU', channel: "Saregama Music" },
  'main-shayar-to-nahin': { id: '3rpVOeCFyWk', channel: "Shailendra Singh - Topic" },
  'mora-gora-ang': { id: 'xfYK0gxAlE8', channel: "Venus Classic" },
  'man-re-tu-kahe': { id: 'VFd0mFXG3YU', channel: "Mohammed Rafi - Topic" },
  'kya-janu-sajan': { id: 'qSNRKH02xoY', channel: "Lata Mangeshkar - Topic" },
  'beeti-na-bitai-raina': { id: 'kfyMS6apDbQ', channel: "Lata Mangeshkar - Topic" },
  'tere-mere-milan': { id: 'Giz_a_YE_V4', channel: "Saregama Music" },
  'teri-bindiya-re': { id: 'E8CMFRFUlu4', channel: "Saregama Music" },
  'is-mod-se-jate-hain': { id: 'EWCp-uGMbH8', channel: "Saregama Music" },
  'aap-yun-faaslon-se': { id: 'ohtItcIA-co', channel: "Lata Mangeshkar - Topic" },
  'aane-wala-pal': { id: 'PikjQIbbBtE', channel: "Saregama Music" },
  'yeh-raat-bheegi': { id: '-wGDnGMfmf8', channel: "Lata Mangeshkar - Topic" },
};
